apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: back-to-cahce
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: cache
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: back
      ports:
        - protocol: TCP
          port: 80
