apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  namespace: app
spec:
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
---
apiVersion: v1
kind: Service
metadata:
  name: back-svc
  namespace: app
spec:
  selector:
    app: back
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
