apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: app
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
---
apiVersion: v1
kind: Service
metadata:
  name: cache-svc
  namespace: app
spec:
  selector:
    app: cache
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
